import { NextRequest, NextResponse } from 'next/server'
import { prisma } from '@/lib/prisma'
import { decrypt } from '@/lib/utils/crypto'

/**
 * GET /api/env/generate?projectId=xxx
 * Generate environment variables file for a project
 */
export async function GET(req: NextRequest) {
  try {
    const projectId = req.nextUrl.searchParams.get('projectId')

    if (!projectId) {
      return NextResponse.json({ error: 'projectId is required' }, { status: 400 })
    }

    const project = await prisma.project.findUnique({
      where: { id: projectId },
      include: {
        integrations: {
          where: { enabled: true }
        }
      }
    })

    if (!project) {
      return NextResponse.json({ error: 'Project not found' }, { status: 404 })
    }

    // Build ENV file content
    let envContent = `# Generated by FrictionlessAuthLayer\n`
    envContent += `# Project: ${project.name}\n`
    envContent += `# Generated at: ${new Date().toISOString()}\n\n`

    // Base configuration
    envContent += `# Application\n`
    envContent += `NEXT_PUBLIC_PROJECT_ID="${project.id}"\n`
    envContent += `NEXT_PUBLIC_PROJECT_SLUG="${project.slug}"\n\n`

    // Add integrations
    for (const integration of project.integrations) {
      const credentials = JSON.parse(decrypt(integration.credentials))

      envContent += `# ${integration.name}\n`

      switch (integration.type) {
        case 'stripe':
          envContent += `STRIPE_SECRET_KEY="${credentials.secret_key}"\n`
          envContent += `NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY="${credentials.publishable_key}"\n`
          envContent += `STRIPE_WEBHOOK_SECRET="${credentials.webhook_secret}"\n\n`
          break

        case 'sendgrid':
          envContent += `SENDGRID_API_KEY="${credentials.api_key}"\n`
          envContent += `SENDGRID_FROM_EMAIL="${credentials.from_email}"\n`
          if (credentials.from_name) {
            envContent += `SENDGRID_FROM_NAME="${credentials.from_name}"\n`
          }
          envContent += `\n`
          break

        case 'oauth_google':
          envContent += `GOOGLE_CLIENT_ID="${credentials.client_id}"\n`
          envContent += `GOOGLE_CLIENT_SECRET="${credentials.client_secret}"\n`
          envContent += `GOOGLE_REDIRECT_URI="${credentials.redirect_uri}"\n\n`
          break

        case 'oauth_github':
          envContent += `GITHUB_CLIENT_ID="${credentials.client_id}"\n`
          envContent += `GITHUB_CLIENT_SECRET="${credentials.client_secret}"\n`
          envContent += `GITHUB_REDIRECT_URI="${credentials.redirect_uri}"\n\n`
          break

        case 'hubspot':
          envContent += `HUBSPOT_API_KEY="${credentials.api_key}"\n\n`
          break

        case 'salesforce':
          envContent += `SALESFORCE_CONSUMER_KEY="${credentials.consumer_key}"\n`
          envContent += `SALESFORCE_CONSUMER_SECRET="${credentials.consumer_secret}"\n`
          envContent += `SALESFORCE_USERNAME="${credentials.username}"\n`
          envContent += `SALESFORCE_PASSWORD="${credentials.password}"\n\n`
          break

        case 'mailchimp':
          envContent += `MAILCHIMP_API_KEY="${credentials.api_key}"\n\n`
          break
      }
    }

    // SmartHooks
    envContent += `# SmartHooks Integration\n`
    envContent += `SMARTHOOKS_WEBHOOK_URL="${process.env.SMARTHOOKS_WEBHOOK_URL}"\n`
    envContent += `SMARTHOOKS_API_KEY="${process.env.SMARTHOOKS_API_KEY}"\n`

    return NextResponse.json({
      content: envContent,
      filename: `.env.${project.slug}`
    })
  } catch (error: any) {
    return NextResponse.json({ error: error.message }, { status: 500 })
  }
}
